name: ci

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: install tauri-cli
        run: |
          cargo install tauri-cli

      - name: build
        run: |
          cargo tauri build

      - name: upload assets
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: LeafVPN-setup.exe
          path: src-tauri\target\release\bundle\nsis\*.exe

      - name: upload assets
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: LeafVPN.dmg
          path: src-tauri/target/release/bundle/dmg/*.dmg
